CREATE DATABASE DB_PERSONEL_TAKIP

USE DB_PERSONEL_TAKIP

CREATE TABLE TBL_EMPLOYEE(
ID INT IDENTITY(1,1) PRIMARY KEY,
AD VARCHAR(30),
SOYAD VARCHAR(30),
DEPARTMAN TINYINT,
CINSIYET BIT
)

CREATE TABLE TBL_DEPARTMENT(
ID TINYINT IDENTITY(1,1) PRIMARY KEY,
AD VARCHAR(50)
)

INSERT INTO TBL_DEPARTMENT(AD) VALUES ('YAZILIM')
INSERT INTO TBL_DEPARTMENT(AD) VALUES ('MUHASEBE')
INSERT INTO TBL_DEPARTMENT(AD) VALUES ('SATIŞ')

INSERT INTO TBL_EMPLOYEE(AD,SOYAD,DEPARTMAN,CINSIYET) VALUES ('AHMET','CAN',2,1)
INSERT INTO TBL_EMPLOYEE(AD,SOYAD,DEPARTMAN,CINSIYET) VALUES ('AYŞE','DEMİR',1,0)
INSERT INTO TBL_EMPLOYEE(AD,SOYAD,DEPARTMAN,CINSIYET) VALUES ('MEHMET','YILMAZ',3,1)

SELECT ID,AD,SOYAD, 
CASE WHEN CINSIYET=1 THEN 'ERKEK' ELSE 'KADIN' END AS CINSIYET, DEPARTMAN FROM TBL_EMPLOYEE

SELECT TBL_EMPLOYEE.AD,SOYAD,TBL_DEPARTMENT.AD AS 'DEPARTMAN' ,CINSIYET FROM TBL_EMPLOYEE INNER JOIN TBL_DEPARTMENT
ON
TBL_DEPARTMENT.ID=TBL_EMPLOYEE.DEPARTMAN 

--CASE VE INNER JOIN BİRLEŞTİRME ÇALIŞMASI

SELECT TBL_EMPLOYEE.AD,SOYAD, TBL_DEPARTMENT.AD AS 'DEPARTMAN',
CASE WHEN CINSIYET=1 THEN 'ERKEK' ELSE 'KADIN' END AS CINSIYET FROM TBL_EMPLOYEE INNER JOIN TBL_DEPARTMENT ON
TBL_DEPARTMENT.ID=TBL_EMPLOYEE.DEPARTMAN

CREATE PROCEDURE VeriListele
AS
SELECT TBL_EMPLOYEE.AD,SOYAD, TBL_DEPARTMENT.AD AS 'DEPARTMAN',
CASE WHEN CINSIYET=1 THEN 'ERKEK' ELSE 'KADIN' END AS CINSIYET FROM TBL_EMPLOYEE INNER JOIN TBL_DEPARTMENT ON
TBL_DEPARTMENT.ID=TBL_EMPLOYEE.DEPARTMAN

execute VeriListele
